version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"
  groups:
    dependencies:
      applies-to: version-updates
      patterns:
      - "*"
